package com.hlidskialf.spellcast.swing;

import com.hlidskialf.spellcast.swing.components.GestureComboBoxRenderer;
import com.hlidskialf.spellcast.swing.components.QuestionPanel;
import com.hlidskialf.spellcast.swing.components.WizardPanel;
import com.hlidskialf.spellcast.swing.dialogs.ChangeNameDialog;
import com.hlidskialf.spellcast.swing.dialogs.JoinGameDialog;
import com.hlidskialf.spellcast.swing.dialogs.ReferenceDialog;
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.LineBasedFrameDecoder;
import io.netty.handler.codec.string.StringDecoder;
import io.netty.handler.codec.string.StringEncoder;
import io.netty.util.CharsetUtil;

import javax.swing.*;
import javax.swing.plaf.metal.MetalComboBoxUI;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.text.DefaultCaret;
import java.awt.*;
import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * Created by wiggins on 1/11/15.
 */
public class SpellcastForm implements NameChangeListener, SpellcastMessage.MessageListener {
    private static JFrame frame;

    private JPanel contentPanel;
    private JTextField chatInput;
    private JTextArea gameLog;
    private JButton sendButton;
    private JPanel playPanel;
    private JComboBox rightComboBox;
    private JComboBox leftComboBox;
    private JPanel inputPanel;
    private JPanel answerPanel;
    private Channel channel;
    private Player wizard;
    private WizardPanel wizardPanel;
    private JMenuItem joinMenuItem;
    private JMenuItem disconnectMenuItem;
    private Map<Player, WizardPanel> opponentPanels;
    private Map<String, Player> opponents;

    private Map<Hand, QuestionPanel> questionPanels;

    private GameState gameState;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridBagLayout());
        playPanel = new JPanel();
        playPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        playPanel.setMinimumSize(new Dimension(10, 450));
        playPanel.setPreferredSize(new Dimension(10, 450));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPanel.add(playPanel, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 10;
        contentPanel.add(scrollPane1, gbc);
        gameLog = new JTextArea();
        gameLog.setColumns(80);
        gameLog.setEditable(false);
        gameLog.setLineWrap(true);
        gameLog.setRows(0);
        scrollPane1.setViewportView(gameLog);
        inputPanel = new JPanel();
        inputPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentPanel.add(inputPanel, gbc);
        leftComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        inputPanel.add(leftComboBox, gbc);
        rightComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        inputPanel.add(rightComboBox, gbc);
        sendButton = new JButton();
        sendButton.setText("Send");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        inputPanel.add(sendButton, gbc);
        chatInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        inputPanel.add(chatInput, gbc);
        answerPanel = new JPanel();
        answerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        inputPanel.add(answerPanel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    enum GameState {
        Disconnected,
        WaitingForMatch,
        ReadyAndWaitingForMatch,
        Watching,
        Gesturing, //waiting for user to submit gestures
        Answering, //still has questions to answer server
    }

    public SpellcastForm() {

        questionPanels = new HashMap<Hand, QuestionPanel>();

        opponentPanels = new HashMap<Player, WizardPanel>();
        opponents = new HashMap<String, Player>();

        wizard = new Player("Wizard");
        wizardPanel = new WizardPanel(wizard);

        playPanel.add(wizardPanel);


        leftComboBox.setModel(new Icons.IconComboBoxModel(Hand.left));
        leftComboBox.setRenderer(new GestureComboBoxRenderer());
        leftComboBox.setUI(new MetalComboBoxUI());

        rightComboBox.setModel(new Icons.IconComboBoxModel(Hand.right));
        rightComboBox.setRenderer(new GestureComboBoxRenderer());
        rightComboBox.setUI(new MetalComboBoxUI());

        DefaultCaret caret = (DefaultCaret) gameLog.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);


//        playPanel.setBorder(BorderFactory.createLineBorder(Color.RED));


        chatInput.addKeyListener(
                new KeyAdapter() {
                    @Override
                    public void keyTyped(final KeyEvent keyEvent) {
                        if (keyEvent.getKeyChar() == KeyEvent.VK_ENTER) {
                            String txt = chatInput.getText().trim();
                            if (!txt.isEmpty()) {
                                say(txt);
                                chatInput.setText("");
                            }
                        }
                    }
                }
        );


        sendButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onSendButton();
            }
        });
    }

    public static void main(String[] args) {

        String appName = System.getProperty("appName");
        if (appName == null) {
            appName = "Spellcast";
        }

        // set up for mac menus
        System.setProperty("apple.laf.useScreenMenuBar", "true");
        System.setProperty("com.apple.mrj.application.apple.menu.about.name", appName);

        try {
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        } catch (Exception E) {

        }

        SpellcastForm form = new SpellcastForm();

        frame = new JFrame(appName);
        frame.setContentPane(form.contentPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setJMenuBar(form.buildMenuBar());


        Container container = frame.getContentPane();
        container.setPreferredSize(new Dimension(700, 700));
        frame.pack();
        frame.setVisible(true);
    }


    public JMenuBar buildMenuBar() {
        JMenuBar menuBar = new JMenuBar();

        JMenu file = new JMenu("Game");

        JMenuItem changeNameItem = new JMenuItem("Change Name");
        changeNameItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onChangeName();
            }
        });
        file.add(changeNameItem);

        joinMenuItem = new JMenuItem("Join Game");
        joinMenuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onJoinGame();
            }
        });
        file.add(joinMenuItem);

        disconnectMenuItem = new JMenuItem("Disconnect");
        disconnectMenuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onDisconnect();
            }
        });
        disconnectMenuItem.setEnabled(false);
        file.add(disconnectMenuItem);

        JMenuItem saveAction = new JMenuItem("Save log...");
        saveAction.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onSaveLog();
            }
        });
        file.add(saveAction);

        file.addSeparator();
        JMenuItem quitAction = new JMenuItem("Quit");
        quitAction.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onQuit();
            }
        });
        file.add(quitAction);
        menuBar.add(file);


        JMenu spells = new JMenu("Spells");
        JMenuItem referenceAction = new JMenuItem("Spell list");
        referenceAction.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                onShowSpells();
            }
        });
        spells.add(referenceAction);
        menuBar.add(spells);


        return menuBar;
    }

    private void onQuit() {
        frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
    }

    private void onChangeName() {
        ChangeNameDialog changeNameDialog = new ChangeNameDialog(this);
        changeNameDialog.pack();
        changeNameDialog.setPlayer(wizard);
        changeNameDialog.setVisible(true);

    }

    private void onJoinGame() {
        JoinGameDialog joinGameDialog = new JoinGameDialog(this);
        joinGameDialog.pack();
        joinGameDialog.setPlayer(wizard);
        joinGameDialog.setVisible(true);
    }

    private void onShowSpells() {
        ReferenceDialog.buildAndShow();
    }

    private void onDisconnect() {
        if (channel != null) {
            channel.close();
        }
    }

    private void onSaveLog() {

    }

    private void onSendButton() {
        if (gameState == GameState.WaitingForMatch) {
            sendMessage("READY");
            sendButton.setText("Yield");
            gameState = GameState.ReadyAndWaitingForMatch;
        } else if (gameState == GameState.ReadyAndWaitingForMatch) {
            sendMessage("YIELD");
            sendButton.setText("Ready");
            gameState = GameState.WaitingForMatch;
        } else if (gameState == GameState.Gesturing) {
            ImageIcon leftItem = (ImageIcon) leftComboBox.getSelectedItem();
            ImageIcon rightItem = (ImageIcon) rightComboBox.getSelectedItem();

            sendMessage("GESTURE " + leftItem.getDescription().charAt(0) + " " + rightItem.getDescription().charAt(0));
        } else if (gameState == GameState.Answering) {
            for (QuestionPanel qp : questionPanels.values()) {
                sendMessage("ANSWER " + qp.getHand() + " " + qp.getAnswer());
            }
            questionPanels.clear();
            answerPanel.removeAll();
        }
    }


    private void sendMessage(String message) {
        if (channel != null) {
            channel.writeAndFlush(message + "\r\n");
        }
    }


    public void connectToServer(String hostname, int port) {
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        Bootstrap b = new Bootstrap();
        b.group(workerGroup);
        b.channel(NioSocketChannel.class);
        b.option(ChannelOption.SO_KEEPALIVE, true);
        b.handler(new ChannelInitializer<SocketChannel>() {
            @Override
            protected void initChannel(final SocketChannel socketChannel) throws Exception {
                socketChannel.pipeline().addLast(new LineBasedFrameDecoder(512))
                        .addLast(new StringDecoder(CharsetUtil.UTF_8))
                        .addLast(new StringEncoder(CharsetUtil.UTF_8))
                        .addLast(new SpellcastClientHandler(SpellcastForm.this));
            }
        });
        b.connect(hostname, port).addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(final ChannelFuture channelFuture) throws Exception {
                channel = channelFuture.channel();
                gameState = GameState.WaitingForMatch;

                syncGameStateUI();
                channel.closeFuture().addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(final ChannelFuture channelFuture) throws Exception {
                        channel = null;
                        gameState = GameState.Disconnected;
                        syncGameStateUI();
                    }
                });
            }
        });
    }

    private void syncGameStateUI() {

        joinMenuItem.setEnabled(gameState == GameState.Disconnected);
        disconnectMenuItem.setEnabled(gameState != GameState.Disconnected);

        if (gameState == GameState.WaitingForMatch) {
            sendButton.setText("Ready");
        } else if (gameState == GameState.ReadyAndWaitingForMatch) {
            sendButton.setText("Yield");
        } else if (gameState == GameState.Disconnected && opponentPanels.size() > 0) {
            for (WizardPanel p : opponentPanels.values()) {
                playPanel.remove(p);
                opponentPanels.remove(p);
            }
            playPanel.revalidate();
            playPanel.repaint();
            opponents.clear();
            sendButton.setText("Connect");
        }

    }

    private void syncQuestionUI() {
        if (gameState == GameState.Answering) {
            sendButton.setText("Answer");
        } else {
            answerPanel.removeAll();
            answerPanel.revalidate();
            answerPanel.repaint();
        }
    }


    public void appendToLog(String line) {
        gameLog.append(line + "\n");
    }

    public void say(String message) {
        if (channel != null) {
            channel.writeAndFlush(message + "\r\n");
        }
    }

    private Player playerByNickname(String nickname) {
        if (nickname == null) {
            return null;
        }
        if (nickname.equals(wizard.getNickname())) {
            return wizard;
        }
        if (opponents.containsKey(nickname)) {
            return opponents.get(nickname);
        }
        Player newPlayer = new Player(nickname);
        opponents.put(nickname, newPlayer);
        return newPlayer;
    }

    private WizardPanel wizardPanelForNickname(String nickname) {
        return wizardPanelForPlayer(playerByNickname(nickname));
    }

    private WizardPanel wizardPanelForPlayer(Player player) {
        if (player == null) {
            return null;
        }
        if (player.equals(wizard)) {
            return wizardPanel;
        }
        if (opponentPanels.containsKey(player)) {
            return opponentPanels.get(player);
        }

        //no panel yet
        WizardPanel panel = new WizardPanel(player);
        opponentPanels.put(player, panel);
        playPanel.add(panel);
        return panel;
    }

    @Override
    public void onNameChanged(String name, String gender) {
        wizard.setName(name);
        wizard.setGender(gender);
        wizardPanel.onNameChanged(wizard.getName(), wizard.getGender());
        if (channel != null) { // connected so tell server our new visible name
            channel.writeAndFlush("NAME " + wizard.getGender() + " :" + wizard.getName() + "\r\n");
        } else {
            wizard.setNickname(name.toLowerCase().replace("\\W", "")); // disconnected so update nickname
        }
    }



    /*
     * Spellcast Messages
     */

    @Override
    public void onWelcome(SpellcastChannel channel, String[] message) {
        channel.writeMessage("NAME " + wizard.getNickname() + " " + wizard.getGender() + " :" + wizard.getName());
    }

    @Override
    public void onHello(SpellcastChannel channel, String[] message) {
        wizard.setNickname(message[2]);

    }

    @Override
    public void onWizardStatus(SpellcastChannel channel, String[] message) {
        // 301 <nick> <hp/maxhp | - | +> <gender> <real name>

        Player player = playerByNickname(message[1]);
        player.setGender(message[3]);
        player.setName(message[4]);

        if ("-".equals(message[2]) || "+".equals(message[2])) {
            //observing

        } else {
            String[] hp = message[2].split("/");
            player.setMaxHP(Integer.valueOf(hp[1]));
            player.setCurrentHP(Integer.valueOf(hp[0]));
        }
        WizardPanel panel = wizardPanelForPlayer(player);
        panel.sync();
    }

    @Override
    public void onMonsterStatus(SpellcastChannel channel, String[] message) {
        // 311 <nickname>+<monsterid> <hp/maxhp> :monster name

    }

    @Override
    public void onMatchStart(SpellcastChannel channel, String[] message) {
        if (gameState == GameState.ReadyAndWaitingForMatch) {
            gameState = GameState.Gesturing;
        }
    }

    @Override
    public void onMatchInProgress(SpellcastChannel channel, String[] message) {

    }

    @Override
    public void onRoundStart(SpellcastChannel channel, String[] message) {

    }

    @Override
    public void onAskForGestures(SpellcastChannel channel, String[] message) {
        // 320 <round-id> <nick>

        if (wizard.getNickname().equals(message[2])) {
            // we were asked for gestures
            gameState = GameState.Gesturing;
            sendButton.setText("Gesture");
        }

    }

    @Override
    public void onGesturesReady(SpellcastChannel channel, String[] message) {

    }

    @Override
    public void onGesturesForRound(SpellcastChannel channel, String[] message) {
        // 331 <round-id> <nickname> <left> <right>

        WizardPanel panel = wizardPanelForNickname(message[2]);
        panel.addGestures(message[3], message[4]);

    }

    @Override
    public void onAskForSpell(SpellcastChannel channel, String[] message) {
        //341 <hand> <spell>  :which spell to cast
        Hand hand = Hand.valueOf(message[1]);
        QuestionPanel qPanel = new QuestionPanel(hand, QuestionPanel.QuestionType.Spell, message[2]);
        questionPanels.put(hand, qPanel);
        answerPanel.add(qPanel);
        gameState = GameState.Answering;
        syncQuestionUI();
    }

    @Override
    public void onSpellOption(SpellcastChannel channel, String[] message) {
        //342 <hand> <spell>  :spell name
        Hand hand = Hand.valueOf(message[1]);
        QuestionPanel qPanel = questionPanels.get(hand);
        if (qPanel != null) {
            qPanel.addOption(message[2]);
        }
    }

    @Override
    public void onSpellOptionsEnd(SpellcastChannel channel, String[] message) {
        //343 <hand>
    }

    @Override
    public void onAskForTarget(SpellcastChannel channel, String[] message) {
        //345 <hand> <spell>  :which target for spell
        Hand hand = Hand.valueOf(message[1]);
        QuestionPanel qPanel = new QuestionPanel(hand, QuestionPanel.QuestionType.Target, message[2]);
        questionPanels.put(hand, qPanel);
        answerPanel.add(qPanel);
        gameState = GameState.Answering;
        syncQuestionUI();
    }

    @Override
    public void onTargetOption(SpellcastChannel channel, String[] message) {
        //346 <hand> <nickname> :visible name
        Hand hand = Hand.valueOf(message[1]);
        QuestionPanel qPanel = questionPanels.get(hand);
        if (qPanel != null) {
            qPanel.addOption(message[2]);
        }
    }

    @Override
    public void onTargetOptionsEnd(SpellcastChannel channel, String[] message) {
        //347 <hand> :end of targets

    }

    @Override
    public void errorNicknameInUse(SpellcastChannel channel, String[] message) {
        String nick = wizard.getNickname();
        int idx = new Random().nextInt(nick.length());
        String newnick = nick.substring(idx) + nick.substring(0, idx) + idx;
        wizard.setNickname(newnick);
        wizard.setName(newnick);
        wizardPanel.onNameChanged(wizard.getName(), wizard.getGender());

        //retry with new nickname
        onWelcome(channel, message);
    }






/*====================================================================================================================*/


}
